enable-admin-container: use 'apiclient set'

diff --git a/enable-admin-container b/enable-admin-container
--- a/enable-admin-container
+++ b/enable-admin-container
@@ -5,11 +5,6 @@
 
 error() {
    echo -e "Error: ${*}\n" >&2
-   cat >&2 <<-EOF
-	You can manually enable the admin container like this:
-	   apiclient -u /settings -m PATCH -d '{"host-containers": {"admin": {"enabled": true}}}'
-	   apiclient -u /tx/commit_and_apply -m POST
-	EOF
    exit 1
 }
 
@@ -17,17 +12,9 @@ if ! command -v apiclient >/dev/null 2>&1; then
    error "can't find 'apiclient'"
 fi
 
-# Use our own transaction so we don't interfere with other changes
-TX="enable-admin-container"
-
-echo "Setting admin container to enabled"
-if ! apiclient -v -u "/settings?tx=${TX}" -m PATCH -d '{"host-containers": {"admin": {"enabled": true}}}'; then
-   error "failed to change enabled setting of admin container"
-fi
-
-echo "Committing and applying changes"
-if ! apiclient -v -u "/tx/commit_and_apply?tx=${TX}" -m POST; then
-   error "failed to commit and apply settings"
+echo "Enabling admin container"
+if ! apiclient set host-containers.admin.enabled=true; then
+   error "failed to enable admin container"
 fi
 
 echo "The admin container is now enabled - it should pull and start soon, and then you can SSH in"
